import '../styles/global.sass';

import { Fira_Mono, Inter } from 'next/font/google';
import Navbar from '../components/Navbar';

const interFont = Inter({
    variable: '--font-inter',
    display: 'swap',
    subsets: ['latin'],
    fallback: ['Arial', 'sans-serif']
});

const firaMonoFont = Fira_Mono({
    variable: '--font-fira-mono',
    weight: ['400', '700'],
    display: 'swap',
    subsets: ['latin'],
    fallback: ['Courier New', 'monospace']
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`bg-neutral-900 text-white font-sans ${interFont.variable} ${firaMonoFont.variable}`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}